### ISSUE TITLE
Version 1.0.4 is broken

### ISSUE THREAD

**Issue by ArthurKa** [TSKsmiley/isodd-or-even#3]
Version 1.0.4 seems to be broken. Please, fix it, so I can try my luck to make type definitions.

**Comment by TSKsmiley** [comment]
Could you please elaborate on how you mean that it is broken

**Comment by ArthurKa** [comment]
Just try to `require('number-oddoreven')` on empty project and it goes like this:
![mintty_H9Kf7cWw8E](https://user-images.githubusercontent.com/16370704/140645192-df470b6b-7adc-41bd-abf0-50624f0b642d.png)

Nevertheless version 1.0.3 works just fine. I guess new amazing code formatting style brought in 1.0.4 does the thing.

**Comment by ArthurKa** [comment]
#4.

**Comment by ArthurKa** [comment]
[#57056](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57056). ¯\\\_(ツ)_/¯
